name: simple-program
version: 0.1.0.0
github: "AuthorName/repo-name"
license: BSD3
author: "Author Name Here"
maintainer: "email@example.com"
copyright: "Author Name Here"
extra-source-files:
  - README.md
description: Please see the README on GitHub at <https://github.com/AuthorName/repo-name#readme>

# Manage your dependencies here.
dependencies:
  - base
  # Testing dependencies.
  - hspec
  - QuickCheck

library:
  source-dirs: src

executables:
  simple-program-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Wpartial-fields
      - -fhide-source-paths
      - -Wno-type-defaults
    dependencies:
      - simple-program

tests:
  simple-program-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Wpartial-fields
      - -fhide-source-paths
      - -Wno-type-defaults
    dependencies:
      - simple-program

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
